### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by arghadipmanna101** [YuweAEC/face-Recognition-Attendance-master#5]
- will add photos
- will add gif
- will stylize the readme
- will add how to contribute

**Comment by arghadipmanna101** [comment]
please assign me under Apertre

**Comment by arghadipmanna101** [comment]
- Original Contributors :
![image](https://github.com/YuweAEC/face-Recognition-Attendance-master/assets/130065095/dbee307a-8e8a-4419-b3f0-e7b4315c5555)

- Contributors in your readme file :
![image](https://github.com/YuweAEC/face-Recognition-Attendance-master/assets/130065095/731ff2a1-2c65-4f3b-82a3-0c93c23d81ed)

Should i change it ?

**Comment by YuweAEC** [comment]
Yes But first make another branch for your changes.
After that I will approve it and merge it .

**Comment by arghadipmanna101** [comment]
Ok. but what i do in contributors name ? in your project there have 2 contributors but in your readme file there have 3 contributors name.

**Comment by YuweAEC** [comment]
In my readme file the contributors are the real project makers and the project contributor the other 1 have contributed in main branch that's why he's there

**Comment by arghadipmanna101** [comment]
ok.

**Comment by arghadipmanna101** [comment]
Give me github account of Nillotpal Mishra and Manwendra Mahato.

**Comment by YuweAEC** [comment]
https://github.com/manwendra-mm - Manwendra Mahato 

https://github.com/nillmishra - Nillotpal Mishra

**Comment by arghadipmanna101** [comment]
ok

**Comment by arghadipmanna101** [comment]
check out the PR.

**Comment by arghadipmanna101** [comment]
I had contribute in your project. But you didn't gave me any tag or point any thing.

**Comment by YuweAEC** [comment]
Labels have been updated, and now these PRs and issues will be under APERTRE'24.
