### ISSUE TITLE
Add new feature : API boxes

### ISSUE THREAD

**Issue by apu52** [YuweAEC/face-Recognition-Attendance-master#6]
**Describe the feature you are requesting**

Hello Sir,
I want to add some cool badges in this repo like
- open issues
- contributor
- open PR
- last commites
this type of cool API badges
It will be very helpful to showcase the stats of your Repo as well as will attract more contributors.
**Additional context(if any)**

![image](https://github.com/sayandippaul/dropling-chatapp/assets/114172928/d629c5df-45db-4ad4-9097-1311e862a2d1)

***Are you contributing under any open-source program ?***

APERTRE'24

**Comment by apu52** [comment]
@YuweAEC Please assign me this issue under APERTRE'24 

Okay you can make changes but in other branches.

**Comment by YuweAEC** [comment]
No currently I'm not contributing because of some emergency

**Comment by apu52** [comment]
> No currently I'm not contributing because of some emergency

Can you please assign me this ??
Or this repo is not anymore part of the APERTRE'24

**Comment by YuweAEC** [comment]
You can contribute

**Comment by YuweAEC** [comment]
Labels have been updated, and now these PRs and issues will be under APERTRE'24.

**Comment by apu52** [comment]
@YuweAEC Can you please add easy/medium/hard labels so that my point will be counted
